### ISSUE TITLE
Invidious team notification

### ISSUE THREAD

**Issue by unixfox** [techmetx11/inv_sig_helper#1]
Hello @techmetx11,

Since we will officially use your project as a core component for running Invidious, we would like to migrate it under the iv-org organization.

I have created a fork here: https://github.com/iv-org/inv_sig_helper. And I have invited you to the repository as a collaborator.

If you could continue your work on the iv-org/inv_sig_helper that would be great. We have plans to create official documentation about inv_sig_helper and create a Docker image for it.

I would like to personally thank you for working on this project and helping the Invidious community.

unixfox

**Comment by techmetx11** [comment]
Sure!
Also thank you
